/*
Copyright (c) 2017-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Dagon is a 3D game engine for D language based on OpenGL 4.0 and SDL2.
 * It features deferred HDR renderer, PBR materials, an event manager,
 * scene manager, asset manager, and entity-component model.
 *
 * Description:
 * The `dagon` package publicly imports all of the Dagon's core modules.
 * Currently Dagon consists of the following packages:
 *
 * - $(LINK2 dagon/core.html, dagon.core) - the core modules and foundational utilities
 *
 * - $(LINK2 dagon/graphics.html, dagon.graphics) - 3D graphics system
 *
 * - $(LINK2 dagon/graphics.html, dagon.compute) - GPU compute system
 *
 * - $(LINK2 dagon/resource.html, dagon.resource) - asset management system
 *
 * - $(LINK2 dagon/render.html, dagon.render) - render pipelines and built-in shaders
 *
 * - $(LINK2 dagon/game.html, dagon.game) - base functionality for building a game
 *
 * - $(LINK2 dagon/ui.html, dagon.ui) - UI components and tools
 *
 * - $(LINK2 dagon/extra.html, dagon.extra) - additional shaders and effects
 *
 * Copyright: Timur Gafarov 2017-2025
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon;

public
{
    import dlib;
    
    import dagon.collision;
    import dagon.compute;
    import dagon.core;
    import dagon.extra;
    import dagon.game;
    import dagon.graphics;
    import dagon.render;
    import dagon.resource;
    import dagon.ui;
}
