/*
Copyright (c) 2017-2022 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.graphics.light;

import std.stdio;
import std.math;
import std.conv;
import std.random;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;
import dlib.math.quaternion;
import dlib.container.array;
import dlib.image.color;

import dagon.core.bindings;
import dagon.graphics.state;
import dagon.graphics.entity;
import dagon.graphics.shadowmap;
import dagon.graphics.csm;

enum LightType
{
    AreaSphere = 1,
    AreaTube = 2,
    Sun = 3,
    Spot = 4
}

class Light: Entity
{
    bool shining;
    Color4f color;
    float volumeRadius; // max light attenuation radius
    float radius;
    float length;
    float energy;
    float spotOuterCutoff;
    float spotInnerCutoff;
    LightType type;
    bool shadowEnabled;
    bool scatteringEnabled;
    float scattering;
    float mediumDensity;
    uint scatteringSamples;
    float scatteringMaxRandomStepOffset;
    bool scatteringUseShadow;
    ShadowMap _shadowMap;
    float diffuse;
    float specular;

    this(EntityManager manager)
    {
        super(manager);
        visible = false;
        castShadow = false;
        shining = true;
        length = 1.0f;
        color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        volumeRadius = 1.0f;
        radius = 0.0f;
        energy = 1.0f;
        spotOuterCutoff = 30.0f;
        spotInnerCutoff = 15.0f;
        type = LightType.AreaSphere;
        shadowEnabled = false;
        scatteringEnabled = false;
        scattering = 0.05f;
        mediumDensity = 0.5f;
        scatteringSamples = 20;
        scatteringMaxRandomStepOffset = 0.2f;
        scatteringUseShadow = false;
        diffuse = 1.0f;
        specular = 1.0f;
    }
    
    ShadowMap shadowMap()
    {
        if (_shadowMap is null && shadowEnabled)
        {
            if (type == LightType.Sun)
                _shadowMap = New!CascadedShadowMap(this, this);
        }
        
        return _shadowMap;
    }
}
