/*
Copyright (c) 2019-2024 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.render.deferred.shaders.environment;

import std.stdio;
import std.math;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;
import dlib.math.interpolation;
import dlib.image.color;
import dlib.text.str;

import dagon.core.bindings;
import dagon.graphics.shader;
import dagon.graphics.state;

class EnvironmentShader: Shader
{
   protected:
    String vs, fs;
    
    ShaderParameter!Matrix4x4f viewMatrix;
    ShaderParameter!Matrix4x4f invViewMatrix;
    ShaderParameter!Matrix4x4f projectionMatrix;
    ShaderParameter!Matrix4x4f invProjectionMatrix;
    ShaderParameter!Vector2f resolution;
    ShaderParameter!float zNear;
    ShaderParameter!float zFar;
    
    ShaderParameter!Color4f fogColor;
    ShaderParameter!float fogStart;
    ShaderParameter!float fogEnd;
    
    ShaderParameter!float ambientEnergy;
    ShaderParameter!Color4f ambientVector;
    ShaderParameter!int ambientTexture;
    ShaderParameter!int ambientTextureCube;
    ShaderSubroutine ambientSubroutine;
    GLuint ambientSubroutineCubemap,
           ambientSubroutineEquirectangularMap,
           ambientSubroutineColor;
    
    ShaderParameter!int colorBuffer;
    ShaderParameter!int depthBuffer;
    ShaderParameter!int normalBuffer;
    ShaderParameter!int pbrBuffer;
    ShaderParameter!int occlusionBuffer;
    ShaderParameter!int haveOcclusionBuffer;
    ShaderParameter!int ambientBRDF;
    ShaderParameter!int haveAmbientBRDF;

   public:
    this(Owner owner)
    {
        vs = Shader.load("data/__internal/shaders/Environment/Environment.vert.glsl");
        fs = Shader.load("data/__internal/shaders/Environment/Environment.frag.glsl");

        auto myProgram = New!ShaderProgram(vs, fs, this);
        super(myProgram, owner);
        
        viewMatrix = createParameter!Matrix4x4f("viewMatrix");
        invViewMatrix = createParameter!Matrix4x4f("invViewMatrix");
        projectionMatrix = createParameter!Matrix4x4f("projectionMatrix");
        invProjectionMatrix = createParameter!Matrix4x4f("invProjectionMatrix");
        resolution = createParameter!Vector2f("resolution");
        zNear = createParameter!float("zNear");
        zFar = createParameter!float("zFar");
        
        fogColor = createParameter!Color4f("fogColor");
        fogStart = createParameter!float("fogStart");
        fogEnd = createParameter!float("fogEnd");
        
        ambientEnergy = createParameter!float("ambientEnergy");
        ambientVector = createParameter!Color4f("ambientVector");
        ambientTexture = createParameter!int("ambientTexture");
        ambientTextureCube = createParameter!int("ambientTextureCube");
        ambientSubroutine = createParameterSubroutine("ambient", ShaderType.Fragment);
        ambientSubroutineCubemap = ambientSubroutine.getIndex("ambientCubemap");
        ambientSubroutineEquirectangularMap = ambientSubroutine.getIndex("ambientEquirectangularMap");
        ambientSubroutineColor = ambientSubroutine.getIndex("ambientColor");
        
        colorBuffer = createParameter!int("colorBuffer");
        depthBuffer = createParameter!int("depthBuffer");
        normalBuffer = createParameter!int("normalBuffer");
        pbrBuffer = createParameter!int("pbrBuffer");
        occlusionBuffer = createParameter!int("occlusionBuffer");
        haveOcclusionBuffer = createParameter!int("haveOcclusionBuffer");
        ambientBRDF = createParameter!int("ambientBRDF");
        haveAmbientBRDF = createParameter!int("haveAmbientBRDF");
    }

    ~this()
    {
        vs.free();
        fs.free();
    }

    override void bindParameters(GraphicsState* state)
    {
        viewMatrix = &state.viewMatrix;
        invViewMatrix = &state.invViewMatrix;
        projectionMatrix = &state.projectionMatrix;
        invProjectionMatrix = &state.invProjectionMatrix;
        resolution = state.resolution;
        zNear = state.zNear;
        zFar = state.zFar;

        // Texture 0 - color buffer
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, state.colorTexture);
        colorBuffer = 0;

        // Texture 1 - depth buffer
        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_2D, state.depthTexture);
        depthBuffer = 1;

        // Texture 2 - normal buffer
        glActiveTexture(GL_TEXTURE2);
        glBindTexture(GL_TEXTURE_2D, state.normalTexture);
        normalBuffer = 2;

        // Texture 3 - pbr buffer
        glActiveTexture(GL_TEXTURE3);
        glBindTexture(GL_TEXTURE_2D, state.pbrTexture);
        pbrBuffer = 3;

        // Textures 4, 5 - environment (equirectangular map, cube map)
        if (state.environment)
        {
            fogColor = state.environment.fogColor;
            fogStart = state.environment.fogStart;
            fogEnd = state.environment.fogEnd;
            ambientEnergy = state.environment.ambientEnergy;

            if (state.environment.ambientMap)
            {
                if (state.environment.ambientMap.isCubemap)
                {
                    glActiveTexture(GL_TEXTURE4);
                    glBindTexture(GL_TEXTURE_2D, 0);
                    ambientTexture = 4;
                    
                    glActiveTexture(GL_TEXTURE5);
                    state.environment.ambientMap.bind();
                    ambientTextureCube = 5;
                    
                    ambientSubroutine.index = ambientSubroutineCubemap;
                }
                else
                {
                    glActiveTexture(GL_TEXTURE4);
                    state.environment.ambientMap.bind();
                    ambientTexture = 4;
                    
                    glActiveTexture(GL_TEXTURE5);
                    glBindTexture(GL_TEXTURE_CUBE_MAP, 0);
                    ambientTextureCube = 5;
                    
                    ambientSubroutine.index = ambientSubroutineEquirectangularMap;
                }
            }
            else
            {
                glActiveTexture(GL_TEXTURE4);
                glBindTexture(GL_TEXTURE_2D, 0);
                ambientTexture = 4;
                
                glActiveTexture(GL_TEXTURE5);
                glBindTexture(GL_TEXTURE_CUBE_MAP, 0);
                ambientTextureCube = 5;
                
                ambientVector = state.environment.ambientColor;
                
                ambientSubroutine.index = ambientSubroutineColor;
            }
        }
        else
        {
            fogColor = Color4f(0.5f, 0.5f, 0.5f, 1.0f);
            fogStart = 0.0f;
            fogEnd = 1000.0f;
            ambientEnergy = 1.0f;
            ambientVector = Color4f(0.5f, 0.5f, 0.5f, 1.0f);
            
            glActiveTexture(GL_TEXTURE4);
            glBindTexture(GL_TEXTURE_2D, 0);
            ambientTexture = 4;
            
            glActiveTexture(GL_TEXTURE5);
            glBindTexture(GL_TEXTURE_CUBE_MAP, 0);
            ambientTextureCube = 5;
            
            ambientSubroutine.index = ambientSubroutineColor;
        }

        // Texture 6 - occlusion buffer
        glActiveTexture(GL_TEXTURE6);
        occlusionBuffer = 6;
        if (glIsTexture(state.occlusionTexture))
        {
            glBindTexture(GL_TEXTURE_2D, state.occlusionTexture);
            haveOcclusionBuffer = true;
        }
        else
        {
            glBindTexture(GL_TEXTURE_2D, 0);
            haveOcclusionBuffer = false;
        }
        
        // Texture 7 - environment BRDF LUT
        glActiveTexture(GL_TEXTURE7);
        ambientBRDF = 7;
        if (state.environment)
        {
            if (state.environment.ambientBRDF)
            {
                state.environment.ambientBRDF.bind();
                haveAmbientBRDF = true;
            }
            else
            {
                glBindTexture(GL_TEXTURE_2D, 0);
                haveAmbientBRDF = false;
            }
        }
        else
        {
            haveAmbientBRDF = false;
        }
        
        glActiveTexture(GL_TEXTURE0);

        super.bindParameters(state);
    }

    override void unbindParameters(GraphicsState* state)
    {
        super.unbindParameters(state);

        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE2);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE3);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE4);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE5);
        glBindTexture(GL_TEXTURE_CUBE_MAP, 0);

        glActiveTexture(GL_TEXTURE6);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE7);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE0);
    }
}
