/*
Copyright (c) 2017 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.graphics.filters.tonemapping;

import derelict.opengl;
import dagon.core.ownership;
import dagon.graphics.postproc;
import dagon.graphics.framebuffer;
import dagon.graphics.texture;
import dagon.graphics.rc;

enum TonemapFunction
{
    Reinhard = 0,
    Hable = 1
}

class PostFilterTonemapping: PostFilter
{
    private string vs = q{
        #version 330 core
        
        uniform mat4 modelViewMatrix;
        uniform mat4 projectionMatrix;

        uniform vec2 viewSize;
        
        layout (location = 0) in vec2 va_Vertex;
        layout (location = 1) in vec2 va_Texcoord;

        out vec2 texCoord;
        
        void main()
        {
            texCoord = va_Texcoord;
            gl_Position = projectionMatrix * modelViewMatrix * vec4(va_Vertex * viewSize, 0.0, 1.0);
        }
    };

    private string fs = q{
        #version 330 core
        
        uniform sampler2D fbColor;
        uniform int tonemapFunction;
        uniform float exposure;
        
        in vec2 texCoord;
        
        out vec4 frag_color;
        
        vec3 hableFunc(vec3 x)
        {
            return ((x * (0.15 * x + 0.1 * 0.5) + 0.2 * 0.02) / (x * (0.15 * x + 0.5) + 0.2 * 0.3)) - 0.02 / 0.3;
        }

        vec3 tonemapHable(vec3 x, float expo)
        {
            vec3 c = x * expo;
            c = hableFunc(c * 2.0) * (1.0 / hableFunc(vec3(11.2)));
            return pow(c, vec3(1.0 / 2.2));
        }
        
        vec3 tonemapReinhard(vec3 x, float expo)
        {
            vec3 c = x * expo;
            c = c / (c + 1.0);
            return pow(c, vec3(1.0 / 2.2));
        }

        void main()
        {            
            vec3 res = texture(fbColor, texCoord).rgb;
            if (tonemapFunction == 1)
                res = tonemapHable(res, exposure);
            else
                res = tonemapReinhard(res, exposure);
            frag_color = vec4(res, 1.0);
        }
    };

    override string vertexShader()
    {
        return vs;
    }

    override string fragmentShader()
    {
        return fs;
    }
    
    GLint tonemapFunctionLoc;
    GLint exposureLoc;
    
    TonemapFunction tonemapFunction = TonemapFunction.Reinhard;
    float exposure = 1.0f;

    this(Framebuffer fb, Owner o)
    {
        super(fb, o);
        
        tonemapFunctionLoc = glGetUniformLocation(shaderProgram, "tonemapFunction");
        exposureLoc = glGetUniformLocation(shaderProgram, "exposure");
    }
    
    override void bind(RenderingContext* rc)
    {
        super.bind(rc);
        
        glUniform1i(tonemapFunctionLoc, tonemapFunction);
        glUniform1f(exposureLoc, exposure);
    }
}
