/*
Copyright (c) 2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module dagon.extra.ocean;

import std.stdio;
import std.math;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;
import dlib.math.interpolation;
import dlib.image.color;
import dlib.text.str;

import dagon.core.bindings;
import dagon.graphics.material;
import dagon.graphics.light;
import dagon.graphics.shader;
import dagon.graphics.state;
import dagon.graphics.texture;
import dagon.graphics.csm;
import dagon.resource.asset;
import dagon.resource.texture;

/*
 * Ocean/sea with Gerstner waves
 */
class OceanShader: Shader
{
   protected:
    String vs, fs;
    
    float time1 = 0.0f;
    float time2 = 0.0f;
    float rippleTime = 0.0f;
    
   public:
    float waveSpeed1 = 0.2f;
    float waveSpeed2 = 0.1f;
    float rippleSpeed = 0.03f;
    
    Texture normalTexture1;
    Texture normalTexture2;
    
    Color4f waterColor = Color4f(0.1f, 0.12f, 0.13f, 1.0f);
    Color4f scatteringColor = Color4f(0.3f, 0.6f, 0.5f, 1.0f);
    Color4f reflectionColor = Color4f(0.7f, 0.8f, 0.9f, 1.0f);

    this(AssetManager assetManager)
    {
        vs = Shader.load("data/__internal/shaders/Ocean/Ocean.vert.glsl");
        fs = Shader.load("data/__internal/shaders/Ocean/Ocean.frag.glsl");
        
        auto prog = New!ShaderProgram(vs, fs, this);
        super(prog, assetManager);
        
        TextureAsset normalTexture1Asset = textureAsset(assetManager, "data/__internal/textures/water_normal1.png");
        normalTexture1 = normalTexture1Asset.texture;

        TextureAsset normalTexture2Asset = textureAsset(assetManager, "data/__internal/textures/water_normal2.png");
        normalTexture2 = normalTexture2Asset.texture;
    }
    
    ~this()
    {
        vs.free();
        fs.free();
    }
    
    override void bindParameters(GraphicsState* state)
    {
        Material mat = state.material;
        
        setParameter("modelViewMatrix", state.modelViewMatrix);
        setParameter("projectionMatrix", state.projectionMatrix);
        setParameter("normalMatrix", state.normalMatrix);
        setParameter("viewMatrix", state.viewMatrix);
        setParameter("invViewMatrix", state.invViewMatrix);
        setParameter("prevModelViewMatrix", state.prevModelViewMatrix);
        setParameter("textureMatrix", mat.textureTransformation);
        
        setParameter("cameraPosition", state.cameraPosition);
        
        setParameter("fogColor", state.environment.fogColor);
        setParameter("fogStart", state.environment.fogStart);
        setParameter("fogEnd", state.environment.fogEnd);
        
        // Sun
        Light sun = mat.sun;
        if (sun is null)
            sun = state.environment.sun;
        
        Vector3f sunDirection = Vector3f(0.0f, 0.0f, 1.0f);
        Color4f sunColor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        float sunEnergy = 1.0f;
        
        if (sun)
        {
            sunDirection = sun.directionAbsolute;
            sunColor = sun.color;
            sunEnergy = sun.energy;
        }
        
        Vector4f sunDirHg = Vector4f(sunDirection);
        sunDirHg.w = 0.0;
        setParameter("sunDirection", (sunDirHg * state.viewMatrix).xyz);
        setParameter("sunColor", sunColor);
        setParameter("sunEnergy", sunEnergy);
        
        // Time
        time1 += state.time.delta * waveSpeed1;
        if (time1 >= 1.0f)
            time1 = 0.0f;
        time2 += state.time.delta * waveSpeed2;
        if (time2 >= 1.0f)
            time2 = 0.0f;
        setParameter("time1", time1);
        setParameter("time2", time2);
        
        rippleTime += state.time.delta * rippleSpeed;
        if (rippleTime >= 1.0f)
            rippleTime = 0.0f;
        setParameter("rippleTime", rippleTime);
        
        setParameter("waterColor", waterColor);
        setParameter("scatteringColor", scatteringColor);
        setParameter("reflectionColor", reflectionColor);
        
        // Normal textures
        glActiveTexture(GL_TEXTURE0);
        normalTexture1.bind();
        setParameter("normalTexture1", 0);

        glActiveTexture(GL_TEXTURE1);
        normalTexture2.bind();
        setParameter("normalTexture2", 1);
        
        super.bindParameters(state);
    }
    
    override void unbindParameters(GraphicsState* state)
    {
        super.unbindParameters(state);
        
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, 0);

        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_2D, 0);
    }
}
