/*
Copyright (c) 2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.core.persistent;

import std.stdio: writeln;
import std.traits;
import std.file;
import std.process;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.stream;
import dlib.math.vector;
import dlib.image.color;
import dlib.text.str;
import dlib.filesystem.filesystem;
import dlib.filesystem.stdfs;

import dagon.core.props;

/*
 * Persistent key-value data storage, uses the same format as dagon.core.config.
 * Files are stored in home directory under Posix and in %APPDATA% directory
 * under Windows (C:\Users\<user>\AppData\Roaming).
 * It can be used to manage application-specific user data, such as preferences
 * and game saves.
 */
class PersistentStorage: Owner
{
    StdFileSystem fs;
    String appDataDir;
    String filename;
    String localFilename;
    Properties props;
    
    this(string appFolder, string filename, Owner o)
    {
        super(o);
        fs = New!StdFileSystem();
        
        string homeDirVar = "";
        version(Windows) homeDirVar = "APPDATA";
        version(Posix) homeDirVar = "~";
        
        string dirSeparator;
        version(Windows) dirSeparator = "\\";
        version(Posix) dirSeparator = "/";
        
        appDataDir = String(environment.get(homeDirVar, ""));
        if (appDataDir.length)
        {
            // Use <appDataDir>/<appFolder>/<filename>
            String output;
            this.filename = String(appDataDir);
            this.filename ~= dirSeparator;
            this.filename ~= appFolder;
            
            fs.createDir(this.filename, true);
            
            this.filename ~= dirSeparator;
            this.filename ~= filename;
        }
        else
        {
            // Use ./<filename>
            this.filename = String(filename);
        }
        
        this.localFilename = String(filename);
        
        writeln("Using persistent storage file: ", this.filename);
        
        props = New!Properties(this);
        load();
    }
    
    ~this()
    {
        appDataDir.free();
        filename.free();
        localFilename.free();
        Delete(fs);
    }
    
    void load()
    {
        FileStat stat;
        if (fs.stat(filename, stat))
        {
            auto istrm = fs.openForInput(filename);
            auto input = readText(istrm);
            Delete(istrm);
            props.parse(input);
            Delete(input);
        }
    }
    
    void save()
    {
        String data = props.serialize();
        
        OutputStream strm = fs.openForOutput(filename, FileSystem.create | FileSystem.truncate);
        strm.writeArray(data);
        strm.close();
        Delete(strm);
        
        data.free();
    }
    
    DProperty opDispatch(string key)()
    {
        return props[key];
    }
    
    void opDispatch(string key, T)(T value)
    {
        bool changed = false;
        static if (is(T == string))
        {
            props.set(DPropType.Number, key, value);
            changed = true;
        }
        else static if (is(T == Vector3f) || is(T == Vector4f) || is(T == Color4f))
        {
            props.set(DPropType.Vector, key, value.toString());
            changed = true;
        }
        else static if (isNumeric!T)
        {
            props.set(DPropType.Number, key, value.to!string);
            changed = true;
        }
        
        if (changed)
            save();
    }
}
