/*
Copyright (c) 2017-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Provides a font asset class.
 *
 * Description:
 * The `dagon.resource.font` module provides the `FontAsset` class that
 * loads a `Font` object from file.
 *
 * Copyright: Copyright (c) 2017-2026 Timur Gafarov
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dagon.resource.font;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.stream;
import dlib.filesystem.filesystem;
import dlib.filesystem.stdfs;

import dagon.core.logger;
import dagon.graphics.font;
import dagon.resource.asset;

/**
 * An `Asset` specialization that loads a `Font` object from file.
 */
class FontAsset: Asset
{
    /// The loaded font object.
    Font font;
    
    /// Memory buffer for storing font data, typically for use with FreeType.
    ubyte[] buffer;

    /**
     * Constructs an `FontAsset`.
     *
     * Params:
     *   height = em height (font size) in pixels.
     *   pixelRatio = target pixel ratio for HiDPI rendering.
     *   owner = The owner object.
     */
    this(uint height, float pixelRatio, Owner o)
    {
        super(o);
        font = New!Font(height, pixelRatio, this);
    }

    /// Destructor. Releases all associated resources.
    ~this()
    {
        release();
    }

    /**
     * Loads the thread-safe part of the font asset from a file.
     *
     * Params:
     *   filename = The asset file name.
     *   istrm    = Input stream for the asset file.
     *   fs       = File system used for loading.
     *   mngr     = Asset manager.
     * Returns:
     *   `true` if the asset was loaded successfully, `false` otherwise.
     */
    override bool loadThreadSafePart(string filename, InputStream istrm, ReadOnlyFileSystem fs, AssetManager assetManager)
    {
        if (assetManager.application.ftLibrary)
        {
            font.ftLibrary = assetManager.application.ftLibrary;
            FileStat s;
            fs.stat(filename, s);
            buffer = New!(ubyte[])(cast(size_t)s.sizeInBytes);
            istrm.fillArray(buffer);
            font.createFromMemory(buffer);
            return true;
        }
        else
        {
            logWarning("FreeType library is not available, font will not be loaded");
            return false;
        }
    }

    /**
     * Loads the thread-unsafe part of the font asset.
     *
     * Returns:
     *   `true` if successful, `false` otherwise.
     */
    override bool loadThreadUnsafePart()
    {
        if (font.ftLibrary)
        {
            font.prepareVAO();
            font.preloadASCII();
            return true;
        }
        else
            return false;
    }

    /// Releases all resources associated with this font asset.
    override void release()
    {
        if (buffer.length)
            Delete(buffer);
    }
}
